"""
Init Project — scaffold a new Narractive project.
"""

from __future__ import annotations

from pathlib import Path

# ---------------------------------------------------------------------------
# Templates (plain string, no Jinja2)
# ---------------------------------------------------------------------------

_CONFIG_TEMPLATE = """\
# Narractive config — generated by `narractive init`
# Edit this file to match your environment.

obs:
  host: localhost
  port: 4455
  password: ''
  scenes:
    main: Main
    intro_scene: Intro
    outro_scene: Outro
  output_dir: ~/Videos/{project_name}
  recording_format: mkv

app:
  window_title: '{app_window}'
  startup_wait: 5
  regions: {{}}

timing:
  click_delay: 0.3
  type_delay: 0.05
  scroll_delay: 0.2
  action_pause: 1.0
  transition_pause: 2.0
  mouse_move_duration: 0.5

diagrams:
  output_dir: output/diagrams
  theme: dark

narration:
  engine: {tts_engine}
  voice: fr-FR-HenriNeural
  output_dir: output/narration

subtitles:
  enabled: true
  max_chars_per_line: 42
  max_lines: 2
  output_dir: output/{{lang}}/subtitles

capture:
  fps: 10
  output_dir: output/captures
  method: import

output:
  final_dir: output/final
  resolution: 2560x1440
  fps: 30
  codec: libx264
  quality: '23'

languages:
{languages_block}
"""

_SEQ_TEMPLATE = """\
\"\"\"Sequence 00 — Intro (generated by narractive init).\"\"\"\
from __future__ import annotations

from video_automation.sequences.base import VideoSequence


class Seq00Intro(VideoSequence):
    sequence_id = 0
    name = "Intro"
    duration_estimate = 10.0

    def run(self, recorder, app, config):
        # TODO: implement your intro sequence
        pass
"""

_NARRATION_TEMPLATE = """\
# Narrations — {lang}
# Generated by `narractive init`

seq00_intro: >
  Welcome to {project_name}.
  This is an automatically generated narration placeholder.
  Edit this file to add your own narration text.
"""

_SEQUENCES_INIT = """\
\"\"\"Sequences package for {project_name}.\"\"\"\
from .seq00_intro import Seq00Intro

SEQUENCES = [Seq00Intro]
"""

_NEXT_STEPS = """\

  Project '{project_name}' created in {project_dir}/

  Next steps:
    1. Edit config.yaml to match your environment (OBS port, app window title, etc.)
    2. Edit sequences/seq00_intro.py to define your sequences
    3. Edit narrations/<lang>.yaml to add your narration text
    4. Run `narractive --config config.yaml --narration` to generate audio
    5. Run `narractive --config config.yaml --all` to record your video

  Useful commands:
    narractive --config config.yaml --list
    narractive --config config.yaml --narration
    narractive --config config.yaml --subtitles --lang {first_lang}
    narractive --config config.yaml --assemble
"""


# ---------------------------------------------------------------------------
# Scaffold function
# ---------------------------------------------------------------------------


def scaffold_project(
    project_dir: Path,
    project_name: str,
    app_window: str,
    tts_engine: str,
    languages: list[str],
    recording_backend: str,
) -> str:
    """
    Create the project directory structure.

    Returns the "next steps" message to display.
    """
    project_dir.mkdir(parents=True, exist_ok=True)

    # Build languages block for config.yaml
    lang_lines = []
    for lang in languages:
        lang_lines.append(f"  {lang}:")
        lang_lines.append("    voice: fr-FR-HenriNeural")
    languages_block = "\n".join(lang_lines)

    # config.yaml
    config_content = _CONFIG_TEMPLATE.format(
        project_name=project_name,
        app_window=app_window,
        tts_engine=tts_engine,
        languages_block=languages_block,
    )
    (project_dir / "config.yaml").write_text(config_content, encoding="utf-8")

    # sequences/__init__.py
    seq_dir = project_dir / "sequences"
    seq_dir.mkdir(exist_ok=True)
    (seq_dir / "__init__.py").write_text(
        _SEQUENCES_INIT.format(project_name=project_name), encoding="utf-8"
    )

    # sequences/seq00_intro.py
    (seq_dir / "seq00_intro.py").write_text(_SEQ_TEMPLATE, encoding="utf-8")

    # narrations/<lang>.yaml
    narr_dir = project_dir / "narrations"
    narr_dir.mkdir(exist_ok=True)
    for lang in languages:
        narr_content = _NARRATION_TEMPLATE.format(lang=lang, project_name=project_name)
        (narr_dir / f"{lang}.yaml").write_text(narr_content, encoding="utf-8")

    first_lang = languages[0] if languages else "fr"
    return _NEXT_STEPS.format(
        project_name=project_name,
        project_dir=project_dir,
        first_lang=first_lang,
    )
